version: "2"
services:
  db:
    image: ccr.ccs.tencentyun.com/lpoj/database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "lpojdatabase" # 选择性修改，如果你有自己的数据库，请忽略
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "./Database/data:/var/lib/mysql"
      - "./Database/conf:/etc/mysql/mysql.conf.d"

  backend1:
    image: ccr.ccs.tencentyun.com/lpoj/backend
    depends_on:
      - db
    links:
      - db:lpojdatabase
    environment:
      DB_PASSWORD: "lpojdatabase" # 选择性修改
      DB_HOST: "lpojdatabase" # 选择性修改
      DB_USER: "root" # 选择性修改
      DB_PORT: 3306 # 选择性修改
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - "./Backend:/Backend"

  backend2:
    image: ccr.ccs.tencentyun.com/lpoj/backend
    depends_on:
      - backend1
    command: gunicorn -w 5 --bind 0.0.0.0:8000 -k 'gevent' Backend.wsgi:application
    links:
      - db:lpojdatabase
    environment:
      DB_PASSWORD: "lpojdatabase" # 选择性修改
      DB_HOST: "lpojdatabase" # 选择性修改
      DB_USER: "root" # 选择性修改
      DB_PORT: 3306 # 选择性修改
    ports:
      - "8001:8000"
    restart: always
    volumes:
      - "./Backend:/Backend"

  backend3:
    image: ccr.ccs.tencentyun.com/lpoj/backend
    depends_on:
      - backend1
    command: gunicorn -w 5 --bind 0.0.0.0:8000 -k 'gevent' Backend.wsgi:application

    links:
      - db:lpojdatabase
    environment:
      DB_PASSWORD: "lpojdatabase" # 选择性修改
      DB_HOST: "lpojdatabase" # 选择性修改
      DB_USER: "root" # 选择性修改
      DB_PORT: 3306 # 选择性修改
    ports:
      - "8002:8000"
    restart: always
    volumes:
      - "./Backend:/Backend"

  frontend:
    image: ccr.ccs.tencentyun.com/lpoj/frontend
    depends_on:
      - backend3
    links:
      - backend1:lpojbackend1
      - backend2:lpojbackend2
      - backend3:lpojbackend3
    ports:
      - "8080:80"
    restart: always
    volumes:
      - "./Frontend/dist/img:/Frontend/dist/img"

  frontendmobile:
    image: ccr.ccs.tencentyun.com/lpoj/frontendmobile
    depends_on:
      - backend3
    links:
      - backend1:lpojbackend1
      - backend2:lpojbackend2
      - backend3:lpojbackend3
    ports:
      - "8081:8081"
    restart: always
    volumes:
      - "./FrontendMobile/dist/img:/FrontendMobile/dist/img"

  judgerserver:
    image: ccr.ccs.tencentyun.com/lpoj/judgerserver
    depends_on:
      - db
    links:
      - db:lpojdatabase
    environment:
      DB_PASSWORD: "lpojdatabase" # 选择性修改
      DB_HOST: "lpojdatabase" # 选择性修改
      DB_USER: "root" # 选择性修改
      DB_PORT: 3306 # 选择性修改
    ports:
      - "9906:9906"
    restart: always

  crawlingserver:
    image: ccr.ccs.tencentyun.com/lpoj/crawlingserver
    depends_on:
      - backend3
    links:
      - db:lpojdatabase
    environment:
      DB_PASSWORD: "lpojdatabase" # 选择性修改
      DB_HOST: "lpojdatabase" # 选择性修改
      DB_USER: "root" # 选择性修改
      DB_PORT: 3306 # 选择性修改
    restart: always

  judger:
    image: ccr.ccs.tencentyun.com/lpoj/judger
    depends_on:
      - judgerserver
    links:
      - judgerserver:lpojjudgerserver
      - db:lpojdatabase
    environment:
      DB_PASSWORD: "lpojdatabase" # 选择性修改
      DB_HOST: "lpojdatabase" # 选择性修改
      DB_USER: "root" # 选择性修改
      DB_PORT: 3306

      SERVER_IP: "lpojjudgerserver"
      SFTP_PORT: 22

      NO_DOWNLOAD: "yes" # 设为yes，则不使用sftp，需要手动将数据压缩包放到Judger/ProblemData中

    restart: always
    volumes:
      - "./Judger/ProblemData:/Judger/ProblemData"

  rsync-server:
    image: axiom/rsync-server
    container_name: rsync-server
    environment:
      USERNAME: "lpojdata"
      PASSWORD: "pass"
      # ALLOW: "172.16.0.0/12 127.0.0.1/32"
    ports:
      - 873:873
    volumes:
      - ./Backend/ProblemData:/data
    restart: always
    tty: true

  # client at the same docker-compose file with server
  rsync-clinet:
    build: ./rsync/client
    container_name: rsync-client
    links:
      - rsync-server
    environment:
      TIMES_PER_SECONDS: 60 # 拉取间隔（s）
      USERNAME: "lpojdata"
      PASSWORD: "pass"
      SERVER: "rsync-server"
      PORT: 873
    volumes:
      - ./Judge/ProblemData:/data
    restart: always
    tty: true
  #
  # A server just circularly copy file locally
  # If you use this, you can remove above tow
  #
  # rsync-localcopy:
  #   build: ./rsync/localcopy
  #   container_name: rsync-localcopy
  #   environment:
  #     TIMES_PER_SECONDS: 60 # 拉取间隔（s）
  #   volumes:
  #     - ./Backend/ProblemData:/FROM_PATH
  #     - ./Judge/ProblemData:/TO_PATH
  #   restart: always
  #   tty: true
